version: "3"
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    working_dir: /opt/app/
    volumes:
      - ./fastapi/:/opt/app/
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
