version: "3"
services:
  fastapi:
    build:
      context: api
      dockerfile: Dockerfile
    working_dir: /opt/app/
    env_file:
      - ./envs/db.env
    volumes:
      - ./api/main.py:/opt/app/main.py
      - ./api/requirements.txt:/opt/app/requirements.txt
      - ./db/:/opt/app/db
      - /tmp/:/tmp/
    ports:
      - "8000:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  postgres:
    image: postgres:15.1
    env_file:
      - ./envs/db.env
    volumes:
      - /data/template-fastapi/:/var/lib/postgresql/data
