version: "3"
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    working_dir: /opt/app/
    env_file:
      - ./envs/db.env
    volumes:
      - ./fastapi/main.py:/opt/app/main.py
      - ./fastapi/requirements.txt:/opt/app/requirements.txt
      - ./db/:/opt/app/db
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:15.1
    env_file:
      - ./envs/db.env
    volumes:
      - /data/template-fastapi/:/var/lib/postgresql/data
